# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160827_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
